export const DEFAULT_COMMIT_TYPES = Object.freeze([
  { type: "✨", section: "Features" },
  { type: "feat", section: "Features" },
  { type: "feature", section: "Features" },
  { type: "🪲", section: "Bug Fixes" },
  { type: "🐛", section: "Bug Fixes" }, // deprecated
  { type: "fix", section: "Bug Fixes" },
  { type: "🏎 ", section: "Performance Improvements" },
  { type: "perf", section: "Performance Improvements" },
  { type: "revert", section: "Reverts" },
  { type: "📚", section: "Documentation", hidden: true },
  { type: "docs", section: "Documentation", hidden: true },
  { type: "💅", section: "Polish", hidden: true },
  { type: "style", section: "Polish", hidden: true },
  { type: "chore", section: "Miscellaneous Chores", hidden: true },
  { type: "♻️", section: "Refactoring", hidden: true },
  { type: "refactor", section: "Refactoring", hidden: true },
  { type: "🚥", section: "Tests", hidden: true },
  { type: "test", section: "Tests", hidden: true },
  { type: "🛠️", section: "Build System", hidden: true },
  { type: "build", section: "Build System", hidden: true },
  { type: "🤖", section: "Continuous Integration", hidden: true },
  { type: "ci", section: "Continuous Integration", hidden: true },
].map(Object.freeze))
